// Generated from Nucleus Profile 2026.pdf on 2026-05-21. Do not edit by hand —
// re-run `python3 scripts/extract-client-roster.py` to regenerate.

import { services } from './site';

export type ServiceSlug = (typeof services)[number]['slug'];

export type ClientRecord = {
  slug: string;
  name: string;
  logoSrc: string;
  industry: string;
  industrySlug: string;
  group: "advisory" | "fundraising";
  services: ServiceSlug[];
  rawServiceLabels: string[];
};

export const CLIENTS: ClientRecord[] = [
  {
    slug: "dcm-shriram",
    name: "DCM Shriram",
    logoSrc: "/brand/clients/agriculture/dcm-shriram.png",
    industry: "Agriculture",
    industrySlug: "agriculture",
    group: "advisory",
    services: ["assurance", "tax-regulatory"],
    rawServiceLabels: ["Limited Review", "Tax Advisory"],
  },
  {
    slug: "dehaat",
    name: "DeHaat",
    logoSrc: "/brand/clients/agriculture/dehaat.png",
    industry: "Agriculture",
    industrySlug: "agriculture",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Process re-engineering", "IFC", "Internal Audit"],
  },
  {
    slug: "iffco",
    name: "National Fertilizers Limited",
    logoSrc: "/brand/clients/agriculture/iffco.png",
    industry: "Agriculture",
    industrySlug: "agriculture",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC"],
  },
  {
    slug: "mastana",
    name: "Mastana",
    logoSrc: "/brand/clients/agriculture/mastana.png",
    industry: "Agriculture",
    industrySlug: "agriculture",
    group: "advisory",
    services: ["risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["Process Audit", "Transfer Pricing"],
  },
  {
    slug: "oagrifarm",
    name: "O'AgriFarm",
    logoSrc: "/brand/clients/agriculture/oagrifarm.png",
    industry: "Agriculture",
    industrySlug: "agriculture",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Assurance"],
  },
  {
    slug: "rfcl",
    name: "Ramagundam Fertilizers",
    logoSrc: "/brand/clients/agriculture/rfcl.png",
    industry: "Agriculture",
    industrySlug: "agriculture",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC"],
  },
  {
    slug: "alpine",
    name: "Alpine",
    logoSrc: "/brand/clients/automobiles-tools/alpine.png",
    industry: "Automobiles & Tools",
    industrySlug: "automobiles-tools",
    group: "advisory",
    services: ["assurance", "risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["IFC", "Assurance", "Transfer Pricing"],
  },
  {
    slug: "borgwarner",
    name: "BorgWarner",
    logoSrc: "/brand/clients/automobiles-tools/borgwarner.png",
    industry: "Automobiles & Tools",
    industrySlug: "automobiles-tools",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC"],
  },
  {
    slug: "sanden",
    name: "Sanden",
    logoSrc: "/brand/clients/automobiles-tools/sanden.png",
    industry: "Automobiles & Tools",
    industrySlug: "automobiles-tools",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Revenue Audit"],
  },
  {
    slug: "si-interpack",
    name: "SI Interpack",
    logoSrc: "/brand/clients/automobiles-tools/si-interpack.png",
    industry: "Automobiles & Tools",
    industrySlug: "automobiles-tools",
    group: "advisory",
    services: ["risk-advisory", "tax-regulatory", "corporate-secretarial", "ma-advisory"],
    rawServiceLabels: ["Internal Audit", "Risk Advisory", "GST", "Corporate Secretarial", "M&A Advisory"],
  },
  {
    slug: "unknown-circle-crane",
    name: "New Swan",
    logoSrc: "/brand/clients/automobiles-tools/unknown-circle-crane.png",
    industry: "Automobiles & Tools",
    industrySlug: "automobiles-tools",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Internal Audit"],
  },
  {
    slug: "bandhan-bank",
    name: "Bandhan Bank",
    logoSrc: "/brand/clients/bfsi/bandhan-bank.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Concurrent Audit"],
  },
  {
    slug: "central-bank-of-india",
    name: "Central Bank of India",
    logoSrc: "/brand/clients/bfsi/central-bank-of-india.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Concurrent Audit"],
  },
  {
    slug: "easypolicy",
    name: "EasyPolicy",
    logoSrc: "/brand/clients/bfsi/easypolicy.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["Internal Audit", "GST Advisory"],
  },
  {
    slug: "ezspend",
    name: "EZspend",
    logoSrc: "/brand/clients/bfsi/ezspend.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["finance-outsourcing", "ma-advisory", "corporate-secretarial"],
    rawServiceLabels: ["ControllershipFinance & Compliance Handling", "Corporate Strategy", "Corporate Secretarial"],
  },
  {
    slug: "hudco",
    name: "HUDCO",
    logoSrc: "/brand/clients/bfsi/hudco.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC Implementation", "IFC Review"],
  },
  {
    slug: "icici-bank",
    name: "ICICI Bank",
    logoSrc: "/brand/clients/bfsi/icici-bank.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Concurrent Audit"],
  },
  {
    slug: "indusind-bank",
    name: "IndusInd Bank",
    logoSrc: "/brand/clients/bfsi/indusind-bank.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Concurrent Audit"],
  },
  {
    slug: "ofbusiness",
    name: "OfBusiness",
    logoSrc: "/brand/clients/bfsi/ofbusiness.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["ma-advisory", "risk-advisory"],
    rawServiceLabels: ["Internal Audit", "Due Diligence"],
  },
  {
    slug: "sk-finance",
    name: "SK Finance",
    logoSrc: "/brand/clients/bfsi/sk-finance.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Internal Audit"],
  },
  {
    slug: "xyzo",
    name: "Oxyzo",
    logoSrc: "/brand/clients/bfsi/xyzo.png",
    industry: "BFSI",
    industrySlug: "bfsi",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Internal Audit"],
  },
  {
    slug: "olx",
    name: "OLX",
    logoSrc: "/brand/clients/e-commerce/olx.png",
    industry: "E-Commerce",
    industrySlug: "e-commerce",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Process reengineering"],
  },
  {
    slug: "ampin-energy",
    name: "Ampin Energy",
    logoSrc: "/brand/clients/energy-power/ampin-energy.png",
    industry: "Energy & Power",
    industrySlug: "energy-power",
    group: "advisory",
    services: ["finance-outsourcing"],
    rawServiceLabels: ["Controllership"],
  },
  {
    slug: "ingeteam",
    name: "Ingeteam",
    logoSrc: "/brand/clients/energy-power/ingeteam.png",
    industry: "Energy & Power",
    industrySlug: "energy-power",
    group: "advisory",
    services: ["risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["IFC", "Transfer Pricing"],
  },
  {
    slug: "m-plus-solar",
    name: "Amplus Solar",
    logoSrc: "/brand/clients/energy-power/m-plus-solar.png",
    industry: "Energy & Power",
    industrySlug: "energy-power",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC"],
  },
  {
    slug: "nhpc",
    name: "NHPC",
    logoSrc: "/brand/clients/energy-power/nhpc.png",
    industry: "Energy & Power",
    industrySlug: "energy-power",
    group: "advisory",
    services: ["risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["IFC Implementation", "IFC review", "Taxation"],
  },
  {
    slug: "unknown-psu-emblem",
    name: "Delhi Transco Limited",
    logoSrc: "/brand/clients/energy-power/unknown-psu-emblem.png",
    industry: "Energy & Power",
    industrySlug: "energy-power",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Internal Audit"],
  },
  {
    slug: "adda",
    name: "Adda",
    logoSrc: "/brand/clients/fashion/adda.png",
    industry: "Fashion",
    industrySlug: "fashion",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC"],
  },
  {
    slug: "belora-paris",
    name: "Belora Paris",
    logoSrc: "/brand/clients/fashion/belora-paris.png",
    industry: "Fashion",
    industrySlug: "fashion",
    group: "advisory",
    services: ["finance-outsourcing", "tax-regulatory", "corporate-secretarial"],
    rawServiceLabels: ["Controllership", "GST", "Corporate Secretarial"],
  },
  {
    slug: "clarks",
    name: "Clarks",
    logoSrc: "/brand/clients/fashion/clarks.png",
    industry: "Fashion",
    industrySlug: "fashion",
    group: "advisory",
    services: ["assurance", "finance-outsourcing", "risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["IndAS", "Risk Advisory-ICFR", "GST Implementation", "Controllership"],
  },
  {
    slug: "welcome-shoes",
    name: "Welcome Shoes",
    logoSrc: "/brand/clients/fashion/welcome-shoes.png",
    industry: "Fashion",
    industrySlug: "fashion",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC"],
  },
  {
    slug: "healthkart",
    name: "HealthKart",
    logoSrc: "/brand/clients/healthcare/healthkart.png",
    industry: "Healthcare",
    industrySlug: "healthcare",
    group: "advisory",
    services: ["risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["Risk Advisory", "Transfer Pricing"],
  },
  {
    slug: "driveassist",
    name: "DriveAssist",
    logoSrc: "/brand/clients/information-technology/driveassist.png",
    industry: "Information Technology",
    industrySlug: "information-technology",
    group: "advisory",
    services: ["finance-outsourcing", "corporate-secretarial"],
    rawServiceLabels: ["Controllership", "Corporate Secretarial"],
  },
  {
    slug: "expedien",
    name: "Expedien",
    logoSrc: "/brand/clients/information-technology/expedien.png",
    industry: "Information Technology",
    industrySlug: "information-technology",
    group: "advisory",
    services: ["finance-outsourcing", "ma-advisory", "corporate-secretarial"],
    rawServiceLabels: ["Controllership-Finance & Compliance Handling", "Corporate Strategy", "Corporate Secretarial"],
  },
  {
    slug: "grabonrent",
    name: "GrabOnRent",
    logoSrc: "/brand/clients/information-technology/grabonrent.png",
    industry: "Information Technology",
    industrySlug: "information-technology",
    group: "advisory",
    services: ["finance-outsourcing", "tax-regulatory"],
    rawServiceLabels: ["Controllership", "GST Audit"],
  },
  {
    slug: "rmgx",
    name: "RMgX",
    logoSrc: "/brand/clients/information-technology/rmgx.png",
    industry: "Information Technology",
    industrySlug: "information-technology",
    group: "advisory",
    services: ["finance-outsourcing", "tax-regulatory", "corporate-secretarial"],
    rawServiceLabels: ["GST Advisory", "Controllership-Finance & Compliance Handling", "Corporate Secretarial"],
  },
  {
    slug: "stellar",
    name: "Stellar",
    logoSrc: "/brand/clients/information-technology/stellar.png",
    industry: "Information Technology",
    industrySlug: "information-technology",
    group: "advisory",
    services: ["risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["Risk Advisory", "IFC", "Transfer Pricing", "GST Advisory"],
  },
  {
    slug: "bhel",
    name: "BHEL",
    logoSrc: "/brand/clients/infrastructure/bhel.png",
    industry: "Infrastructure",
    industrySlug: "infrastructure",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC Review"],
  },
  {
    slug: "hscc",
    name: "HSCC",
    logoSrc: "/brand/clients/infrastructure/hscc.png",
    industry: "Infrastructure",
    industrySlug: "infrastructure",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC review"],
  },
  {
    slug: "nbcc",
    name: "NBCC",
    logoSrc: "/brand/clients/infrastructure/nbcc.png",
    industry: "Infrastructure",
    industrySlug: "infrastructure",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC Implementation"],
  },
  {
    slug: "railtel",
    name: "RailTel",
    logoSrc: "/brand/clients/infrastructure/railtel.png",
    industry: "Infrastructure",
    industrySlug: "infrastructure",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["IndAS"],
  },
  {
    slug: "rgk",
    name: "Ruby General Hospital",
    logoSrc: "/brand/clients/infrastructure/rgk.png",
    industry: "Infrastructure",
    industrySlug: "infrastructure",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Statutory Audit"],
  },
  {
    slug: "alliance-energy-efficient-economy",
    name: "Alliance for an Energy-Efficient Economy",
    logoSrc: "/brand/clients/non-profits/alliance-energy-efficient-economy.png",
    industry: "Non-Profits",
    industrySlug: "non-profits",
    group: "advisory",
    services: ["finance-outsourcing"],
    rawServiceLabels: ["Controllership"],
  },
  {
    slug: "unknown-sphere",
    name: "Pragati Power Corporation Limited",
    logoSrc: "/brand/clients/non-profits/unknown-sphere.png",
    industry: "Non-Profits",
    industrySlug: "non-profits",
    group: "advisory",
    services: ["assurance", "tax-regulatory"],
    rawServiceLabels: ["PPE Verification", "Transfer Pricing"],
  },
  {
    slug: "ywca",
    name: "YWCA",
    logoSrc: "/brand/clients/non-profits/ywca.png",
    industry: "Non-Profits",
    industrySlug: "non-profits",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Internal Audit"],
  },
  {
    slug: "desbro",
    name: "Desbro",
    logoSrc: "/brand/clients/other-manufacturing/desbro.png",
    industry: "Other Manufacturing",
    industrySlug: "other-manufacturing",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Internal Audit"],
  },
  {
    slug: "kei-wires-cables",
    name: "KEI Wires & Cables",
    logoSrc: "/brand/clients/other-manufacturing/kei-wires-cables.png",
    industry: "Other Manufacturing",
    industrySlug: "other-manufacturing",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC Implementation"],
  },
  {
    slug: "khanna",
    name: "Khanna Paper Mills",
    logoSrc: "/brand/clients/other-manufacturing/khanna.png",
    industry: "Other Manufacturing",
    industrySlug: "other-manufacturing",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Internal Audit"],
  },
  {
    slug: "kommerling",
    name: "Kömmerling",
    logoSrc: "/brand/clients/other-manufacturing/kommerling.png",
    industry: "Other Manufacturing",
    industrySlug: "other-manufacturing",
    group: "advisory",
    services: ["risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["IFC Implementation", "GST Advisory"],
  },
  {
    slug: "pernod-ricard-india",
    name: "Pernod Ricard India",
    logoSrc: "/brand/clients/other-manufacturing/pernod-ricard-india.png",
    industry: "Other Manufacturing",
    industrySlug: "other-manufacturing",
    group: "advisory",
    services: ["assurance", "risk-advisory", "tax-regulatory"],
    rawServiceLabels: ["IFC Implementation", "GST Advisory", "Special Audit"],
  },
  {
    slug: "si-autopack",
    name: "SI Autopack",
    logoSrc: "/brand/clients/other-manufacturing/si-autopack.png",
    industry: "Other Manufacturing",
    industrySlug: "other-manufacturing",
    group: "advisory",
    services: ["ma-advisory", "finance-outsourcing", "tax-regulatory"],
    rawServiceLabels: ["M&A Advisory", "vCFO", "GST"],
  },
  {
    slug: "roam-group",
    name: "Roam Group",
    logoSrc: "/brand/clients/other-manufacturing/roam-group.png",
    industry: "Other Manufacturing",
    industrySlug: "other-manufacturing",
    group: "advisory",
    services: ["ma-advisory", "tax-regulatory"],
    rawServiceLabels: ["M&A Advisory", "GST"],
  },
  {
    slug: "felix",
    name: "Felix",
    logoSrc: "/brand/clients/pharmaceutical/felix.png",
    industry: "Pharmaceutical",
    industrySlug: "pharmaceutical",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["IFC"],
  },
  {
    slug: "valence-labs",
    name: "Valence Labs",
    logoSrc: "/brand/clients/pharmaceutical/valence-labs.png",
    industry: "Pharmaceutical",
    industrySlug: "pharmaceutical",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Statutory Audit"],
  },
  {
    slug: "oxford-university-press",
    name: "Oxford University Press",
    logoSrc: "/brand/clients/publishing/oxford-university-press.png",
    industry: "Publishing",
    industrySlug: "publishing",
    group: "advisory",
    services: ["risk-advisory"],
    rawServiceLabels: ["Process Re-Engineering"],
  },
  {
    slug: "phi",
    name: "PHI Learning",
    logoSrc: "/brand/clients/publishing/phi.png",
    industry: "Publishing",
    industrySlug: "publishing",
    group: "advisory",
    services: ["assurance", "corporate-secretarial"],
    rawServiceLabels: ["Statutory Audit", "Corporate Secretarial"],
  },
  {
    slug: "accor-hotels",
    name: "Accor Hotels",
    logoSrc: "/brand/clients/qsr-hospitality/accor-hotels.png",
    industry: "QSR & Hospitality",
    industrySlug: "qsr-hospitality",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["ControllershipAudit Support"],
  },
  {
    slug: "c-and-co",
    name: "Cafeteria & Co.",
    logoSrc: "/brand/clients/qsr-hospitality/c-and-co.png",
    industry: "QSR & Hospitality",
    industrySlug: "qsr-hospitality",
    group: "advisory",
    services: ["finance-outsourcing"],
    rawServiceLabels: ["Controllership"],
  },
  {
    slug: "qds",
    name: "QD's",
    logoSrc: "/brand/clients/qsr-hospitality/qds.png",
    industry: "QSR & Hospitality",
    industrySlug: "qsr-hospitality",
    group: "advisory",
    services: ["assurance", "finance-outsourcing", "tax-regulatory"],
    rawServiceLabels: ["Assurance", "GST Advisory", "Controllership"],
  },
  {
    slug: "orange-twigs-cafe",
    name: "The Orange Twigs Cafe",
    logoSrc: "/brand/clients/qsr-hospitality/orange-twigs-cafe.png",
    industry: "QSR & Hospitality",
    industrySlug: "qsr-hospitality",
    group: "advisory",
    services: ["finance-outsourcing"],
    rawServiceLabels: ["Controllership"],
  },
  {
    slug: "wanderburgs",
    name: "WanderBurgs",
    logoSrc: "/brand/clients/qsr-hospitality/wanderburgs.png",
    industry: "QSR & Hospitality",
    industrySlug: "qsr-hospitality",
    group: "advisory",
    services: ["finance-outsourcing"],
    rawServiceLabels: ["Controllership"],
  },
  {
    slug: "bsnl",
    name: "BSNL",
    logoSrc: "/brand/clients/telecom/bsnl.png",
    industry: "Telecom",
    industrySlug: "telecom",
    group: "advisory",
    services: ["assurance"],
    rawServiceLabels: ["Statutory Audit"],
  },
  {
    slug: "vodafone",
    name: "Vodafone",
    logoSrc: "/brand/clients/telecom/vodafone.png",
    industry: "Telecom",
    industrySlug: "telecom",
    group: "advisory",
    services: ["tax-regulatory"],
    rawServiceLabels: ["GST Advisory"],
  },
  {
    slug: "barq-mobility",
    name: "Barq Mobility",
    logoSrc: "/brand/clients/transaction-advisory/barq-mobility.png",
    industry: "Transaction Advisory",
    industrySlug: "transaction-advisory",
    group: "advisory",
    services: ["investment-banking"],
    rawServiceLabels: ["Investor Pitch Deck", "Business Plan"],
  },
  {
    slug: "bier-garten",
    name: "Bier Garten",
    logoSrc: "/brand/clients/transaction-advisory/bier-garten.png",
    industry: "Transaction Advisory",
    industrySlug: "transaction-advisory",
    group: "advisory",
    services: ["investment-banking", "ma-advisory", "valuations"],
    rawServiceLabels: ["Information Memorandum", "Financial Due Diligence", "Financial Modeling", "Valuation", "Investor Targeting"],
  },
  {
    slug: "rizek",
    name: "Rizek",
    logoSrc: "/brand/clients/transaction-advisory/rizek.png",
    industry: "Transaction Advisory",
    industrySlug: "transaction-advisory",
    group: "advisory",
    services: ["ma-advisory"],
    rawServiceLabels: ["Investor Due Diligence"],
  },
  {
    slug: "syook",
    name: "Syook",
    logoSrc: "/brand/clients/transaction-advisory/syook.png",
    industry: "Transaction Advisory",
    industrySlug: "transaction-advisory",
    group: "advisory",
    services: ["investment-banking", "valuations"],
    rawServiceLabels: ["Diligence", "Financial Modeling", "Valuation", "Investor Targeting"],
  },
  {
    slug: "unknown-auto-wrench",
    name: "Unknown — to confirm",
    logoSrc: "/brand/clients/transaction-advisory/unknown-auto-wrench.png",
    industry: "Transaction Advisory",
    industrySlug: "transaction-advisory",
    group: "advisory",
    services: ["investment-banking", "valuations"],
    rawServiceLabels: ["Financial Modeling", "Valuation", "Investor Targeting"],
  },
  {
    slug: "vaidyopchar",
    name: "Vaidyopchar",
    logoSrc: "/brand/clients/transaction-advisory/vaidyopchar.png",
    industry: "Transaction Advisory",
    industrySlug: "transaction-advisory",
    group: "advisory",
    services: ["investment-banking"],
    rawServiceLabels: ["Pitch Deck"],
  },
  {
    slug: "vdi",
    name: "VDI",
    logoSrc: "/brand/clients/transaction-advisory/vdi.png",
    industry: "Transaction Advisory",
    industrySlug: "transaction-advisory",
    group: "advisory",
    services: ["investment-banking", "ma-advisory", "valuations"],
    rawServiceLabels: ["Due Diligence", "Feasibility Study", "Valuation"],
  },
  {
    slug: "xfurbish",
    name: "Xfurbish",
    logoSrc: "/brand/clients/transaction-advisory/xfurbish.png",
    industry: "Transaction Advisory",
    industrySlug: "transaction-advisory",
    group: "advisory",
    services: ["investment-banking", "valuations"],
    rawServiceLabels: ["Pitch Deck", "Financial Modeling", "Valuation"],
  },
  {
    slug: "cusmat",
    name: "Cusmat",
    logoSrc: "/brand/clients/fundraising/ar-vr-tech/cusmat.png",
    industry: "AR / VR Tech",
    industrySlug: "ar-vr-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "trezi",
    name: "Trezi",
    logoSrc: "/brand/clients/fundraising/ar-vr-tech/trezi.png",
    industry: "AR / VR Tech",
    industrySlug: "ar-vr-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "dave-ai",
    name: "Dave AI",
    logoSrc: "/brand/clients/fundraising/b2b/dave-ai.png",
    industry: "B2B",
    industrySlug: "b2b",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "kredily",
    name: "Kredily",
    logoSrc: "/brand/clients/fundraising/b2b/kredily.png",
    industry: "B2B",
    industrySlug: "b2b",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "limechat",
    name: "LimeChat",
    logoSrc: "/brand/clients/fundraising/b2b/limechat.png",
    industry: "B2B",
    industrySlug: "b2b",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "mobigarage",
    name: "MobiGarage",
    logoSrc: "/brand/clients/fundraising/b2b/mobigarage.png",
    industry: "B2B",
    industrySlug: "b2b",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "nayam-cloud",
    name: "Nayam (TBC)",
    logoSrc: "/brand/clients/fundraising/b2b/nayam-cloud.png",
    industry: "B2B",
    industrySlug: "b2b",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "pickmywork",
    name: "PickMyWork",
    logoSrc: "/brand/clients/fundraising/b2b/pickmywork.png",
    industry: "B2B",
    industrySlug: "b2b",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "sapio-analytics",
    name: "Sapio Analytics",
    logoSrc: "/brand/clients/fundraising/b2b/sapio-analytics.png",
    industry: "B2B",
    industrySlug: "b2b",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "ecoratings",
    name: "EcoRatings",
    logoSrc: "/brand/clients/fundraising/climate-tech/ecoratings.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "inficold",
    name: "Inficold",
    logoSrc: "/brand/clients/fundraising/climate-tech/inficold.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "minionlabs",
    name: "MinionLabs",
    logoSrc: "/brand/clients/fundraising/climate-tech/minionlabs.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "regrip",
    name: "ReGrip",
    logoSrc: "/brand/clients/fundraising/climate-tech/regrip.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "scrap-uncle",
    name: "ScrapUncle",
    logoSrc: "/brand/clients/fundraising/climate-tech/scrap-uncle.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "sharaksha-ecosolutions",
    name: "Sharaksha Ecosolutions",
    logoSrc: "/brand/clients/fundraising/climate-tech/sharaksha-ecosolutions.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "sheru",
    name: "SHERU",
    logoSrc: "/brand/clients/fundraising/climate-tech/sheru.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "skilancer-solar",
    name: "Skilancer Solar",
    logoSrc: "/brand/clients/fundraising/climate-tech/skilancer-solar.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "sustvest",
    name: "SustVest",
    logoSrc: "/brand/clients/fundraising/climate-tech/sustvest.png",
    industry: "Climate-Tech",
    industrySlug: "climate-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "growfitter",
    name: "Growfitter",
    logoSrc: "/brand/clients/fundraising/consumer-tech/growfitter.png",
    industry: "Consumer Tech",
    industrySlug: "consumer-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "hoopr",
    name: "hoopr",
    logoSrc: "/brand/clients/fundraising/consumer-tech/hoopr.png",
    industry: "Consumer Tech",
    industrySlug: "consumer-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "zingbus",
    name: "zingbus",
    logoSrc: "/brand/clients/fundraising/consumer-tech/zingbus.png",
    industry: "Consumer Tech",
    industrySlug: "consumer-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "burger-singh",
    name: "Burger Singh",
    logoSrc: "/brand/clients/fundraising/d2c-fmcg/burger-singh.png",
    industry: "D2C FMCG",
    industrySlug: "d2c-fmcg",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "burgerama",
    name: "Burgerama",
    logoSrc: "/brand/clients/fundraising/d2c-fmcg/burgerama.png",
    industry: "D2C FMCG",
    industrySlug: "d2c-fmcg",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "mitra",
    name: "Mitra",
    logoSrc: "/brand/clients/fundraising/d2c-fmcg/mitra.png",
    industry: "D2C FMCG",
    industrySlug: "d2c-fmcg",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "power-gummies",
    name: "Power Gummies",
    logoSrc: "/brand/clients/fundraising/d2c-fmcg/power-gummies.png",
    industry: "D2C FMCG",
    industrySlug: "d2c-fmcg",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "proost",
    name: "PROOST",
    logoSrc: "/brand/clients/fundraising/d2c-fmcg/proost.png",
    industry: "D2C FMCG",
    industrySlug: "d2c-fmcg",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "samosa-party",
    name: "Samosa Party",
    logoSrc: "/brand/clients/fundraising/d2c-fmcg/samosa-party.png",
    industry: "D2C FMCG",
    industrySlug: "d2c-fmcg",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "skippi",
    name: "Skippi",
    logoSrc: "/brand/clients/fundraising/d2c-fmcg/skippi.png",
    industry: "D2C FMCG",
    industrySlug: "d2c-fmcg",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "supply-unknown",
    name: "Supply (TBC)",
    logoSrc: "/brand/clients/fundraising/d2c-fmcg/supply-unknown.png",
    industry: "D2C FMCG",
    industrySlug: "d2c-fmcg",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "enercomp",
    name: "EnerComp",
    logoSrc: "/brand/clients/fundraising/drone-tech/enercomp.png",
    industry: "Drone Tech",
    industrySlug: "drone-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "flying-wedge",
    name: "Flying Wedge",
    logoSrc: "/brand/clients/fundraising/drone-tech/flying-wedge.png",
    industry: "Drone Tech",
    industrySlug: "drone-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "indrones",
    name: "inDrones",
    logoSrc: "/brand/clients/fundraising/drone-tech/indrones.png",
    industry: "Drone Tech",
    industrySlug: "drone-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "inside-fpv",
    name: "Inside FPV",
    logoSrc: "/brand/clients/fundraising/drone-tech/inside-fpv.png",
    industry: "Drone Tech",
    industrySlug: "drone-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "saw",
    name: "SAW",
    logoSrc: "/brand/clients/fundraising/drone-tech/saw.png",
    industry: "Drone Tech",
    industrySlug: "drone-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "skyeair",
    name: "SkyeAir",
    logoSrc: "/brand/clients/fundraising/drone-tech/skyeair.png",
    industry: "Drone Tech",
    industrySlug: "drone-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "skylark-drones",
    name: "Skylark Drones",
    logoSrc: "/brand/clients/fundraising/drone-tech/skylark-drones.png",
    industry: "Drone Tech",
    industrySlug: "drone-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "autonxt",
    name: "AutoNxt",
    logoSrc: "/brand/clients/fundraising/ev/autonxt.png",
    industry: "EV",
    industrySlug: "ev",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "zypp-electric",
    name: "Zypp Electric",
    logoSrc: "/brand/clients/fundraising/ev/zypp-electric.png",
    industry: "EV",
    industrySlug: "ev",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "finaleap",
    name: "Finaleap",
    logoSrc: "/brand/clients/fundraising/fin-tech/finaleap.png",
    industry: "Fin-Tech",
    industrySlug: "fin-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "savart",
    name: "Savart",
    logoSrc: "/brand/clients/fundraising/fin-tech/savart.png",
    industry: "Fin-Tech",
    industrySlug: "fin-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "carterx",
    name: "CarterX",
    logoSrc: "/brand/clients/fundraising/logistic-tech/carterx.png",
    industry: "Logistic Tech",
    industrySlug: "logistic-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "oorjaa",
    name: "OORJAA",
    logoSrc: "/brand/clients/fundraising/logistic-tech/oorjaa.png",
    industry: "Logistic Tech",
    industrySlug: "logistic-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "supplynote",
    name: "SupplyNote",
    logoSrc: "/brand/clients/fundraising/logistic-tech/supplynote.png",
    industry: "Logistic Tech",
    industrySlug: "logistic-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "wherehouse",
    name: "Wherehouse",
    logoSrc: "/brand/clients/fundraising/logistic-tech/wherehouse.png",
    industry: "Logistic Tech",
    industrySlug: "logistic-tech",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "astrophel-aerospace",
    name: "Astrophel Aerospace",
    logoSrc: "/brand/clients/fundraising/others/astrophel-aerospace.png",
    industry: "Others",
    industrySlug: "others",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "brainwired",
    name: "brainwired",
    logoSrc: "/brand/clients/fundraising/others/brainwired.png",
    industry: "Others",
    industrySlug: "others",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "geekster",
    name: "Geekster",
    logoSrc: "/brand/clients/fundraising/others/geekster.png",
    industry: "Others",
    industrySlug: "others",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "neural-defend",
    name: "Neural Defend",
    logoSrc: "/brand/clients/fundraising/others/neural-defend.png",
    industry: "Others",
    industrySlug: "others",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "quickreel",
    name: "Quickreel",
    logoSrc: "/brand/clients/fundraising/others/quickreel.png",
    industry: "Others",
    industrySlug: "others",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "relata",
    name: "Relata",
    logoSrc: "/brand/clients/fundraising/others/relata.png",
    industry: "Others",
    industrySlug: "others",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "settl",
    name: "Settl",
    logoSrc: "/brand/clients/fundraising/others/settl.png",
    industry: "Others",
    industrySlug: "others",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
  {
    slug: "social-hardware",
    name: "Social Hardware",
    logoSrc: "/brand/clients/fundraising/others/social-hardware.png",
    industry: "Others",
    industrySlug: "others",
    group: "fundraising",
    services: ["investment-banking"],
    rawServiceLabels: [],
  },
];
